<#
Packaging helper for Android client (Kivy / Buildozer).
Usage:
    .\assemble-android.ps1 -Configuration Release -OutputPath ..\artifacts

This script looks for APK files generated by Buildozer and copies them to the artifacts folder.
#>
param(
    [string]$Configuration = "Release",
    [string]$OutputPath = "..\artifacts"
)

Set-StrictMode -Version Latest
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Definition
Push-Location $ScriptDir

# Buildozer outputs APK to bin/ directory
$apkPattern = "bin/*.apk"
$aabPattern = "bin/*.aab"

$apk = Get-ChildItem -Path $apkPattern -Recurse -ErrorAction SilentlyContinue | Select-Object -Last 1
$aab = Get-ChildItem -Path $aabPattern -Recurse -ErrorAction SilentlyContinue | Select-Object -Last 1

if (-not $apk -and -not $aab) {
    Write-Warning "No APK/AAB found. Attempting to run build script first."
    & "$ScriptDir\build-android.ps1" -Configuration $Configuration
    $apk = Get-ChildItem -Path $apkPattern -Recurse -ErrorAction SilentlyContinue | Select-Object -Last 1
    $aab = Get-ChildItem -Path $aabPattern -Recurse -ErrorAction SilentlyContinue | Select-Object -Last 1
}

if (-not $apk -and -not $aab) {
    Write-Error "No APK/AAB found after build. Aborting packaging."
    Pop-Location
    exit 1
}

$artifactDir = Resolve-Path (Join-Path $ScriptDir $OutputPath)
if (-not (Test-Path $artifactDir)) { New-Item -ItemType Directory -Path $artifactDir | Out-Null }

if ($aab) {
    $dest = Join-Path $artifactDir $aab.Name
    Copy-Item $aab.FullName $dest -Force
    Write-Host "Copied AAB to $dest"
} else {
    $dest = Join-Path $artifactDir $apk.Name
    Copy-Item $apk.FullName $dest -Force
    Write-Host "Copied APK to $dest"
}

Pop-Location
